/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class Registration_Form extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pstmt;
    /**
     * Creates new form Registration_Form
     */
    public Registration_Form() {
        initComponents();
        conn=Connection_Manager.ConnectDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        reg_uname = new javax.swing.JTextField();
        reg_pass = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        register_btn = new javax.swing.JLabel();
        reg_lname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        reg_fname = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        reg_pass_confirm = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        reg_email = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();

        jPanel6.setBackground(new java.awt.Color(69, 123, 157));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setBackground(new java.awt.Color(69, 123, 157));
        username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        username.setBorder(null);
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
        });
        jPanel6.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, 30));

        password.setBackground(new java.awt.Color(69, 123, 157));
        password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setBorder(null);
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        jPanel6.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 200, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 200, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_lock_20px.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_user_20px.png"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 20, 20));

        jPanel2.setBackground(new java.awt.Color(69, 123, 157));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 90, 30));

        jPanel3.setBackground(new java.awt.Color(69, 123, 157));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Forgot Password?");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 53, 87));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 30, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(647, 350));

        jPanel5.setBackground(new java.awt.Color(29, 53, 87));
        jPanel5.setPreferredSize(new java.awt.Dimension(319, 219));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_boarding_pass_95px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("C i t y P a s s");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(69, 123, 157));
        jPanel7.setPreferredSize(new java.awt.Dimension(330, 304));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reg_uname.setBackground(new java.awt.Color(69, 123, 157));
        reg_uname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_uname.setForeground(new java.awt.Color(255, 255, 255));
        reg_uname.setText("Username");
        reg_uname.setBorder(null);
        reg_uname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_unameFocusGained(evt);
            }
        });
        reg_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_unameActionPerformed(evt);
            }
        });
        jPanel7.add(reg_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 200, 20));

        reg_pass.setBackground(new java.awt.Color(69, 123, 157));
        reg_pass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_pass.setForeground(new java.awt.Color(255, 255, 255));
        reg_pass.setText("Password");
        reg_pass.setBorder(null);
        reg_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_passFocusGained(evt);
            }
        });
        reg_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_passActionPerformed(evt);
            }
        });
        jPanel7.add(reg_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 200, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 200, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_email_open_20px.png"))); // NOI18N
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 20, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_user_20px.png"))); // NOI18N
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 20, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(29, 53, 87));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 30, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 53, 87));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_minus_20px.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 20, 30));

        jPanel8.setBackground(new java.awt.Color(69, 123, 157));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        register_btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        register_btn.setForeground(new java.awt.Color(255, 255, 255));
        register_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register_btn.setText("Register");
        register_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, 30));

        reg_lname.setBackground(new java.awt.Color(69, 123, 157));
        reg_lname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_lname.setForeground(new java.awt.Color(255, 255, 255));
        reg_lname.setBorder(null);
        reg_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_lnameFocusGained(evt);
            }
        });
        reg_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_lnameActionPerformed(evt);
            }
        });
        jPanel7.add(reg_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 90, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_identification_documents_20px.png"))); // NOI18N
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 20, 20));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, 10));

        reg_fname.setBackground(new java.awt.Color(69, 123, 157));
        reg_fname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_fname.setForeground(new java.awt.Color(255, 255, 255));
        reg_fname.setBorder(null);
        reg_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_fnameFocusGained(evt);
            }
        });
        reg_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_fnameActionPerformed(evt);
            }
        });
        jPanel7.add(reg_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Last Name");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 20));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("First Name");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        reg_pass_confirm.setBackground(new java.awt.Color(69, 123, 157));
        reg_pass_confirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_pass_confirm.setForeground(new java.awt.Color(255, 255, 255));
        reg_pass_confirm.setText("Password");
        reg_pass_confirm.setBorder(null);
        reg_pass_confirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_pass_confirmFocusGained(evt);
            }
        });
        reg_pass_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_pass_confirmActionPerformed(evt);
            }
        });
        jPanel7.add(reg_pass_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, 20));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 200, 10));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_lock_20px.png"))); // NOI18N
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 20, 20));

        reg_email.setBackground(new java.awt.Color(69, 123, 157));
        reg_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg_email.setForeground(new java.awt.Color(255, 255, 255));
        reg_email.setText("Email Address");
        reg_email.setBorder(null);
        reg_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_emailFocusGained(evt);
            }
        });
        jPanel7.add(reg_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, 20));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 200, 10));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/images/icons8_checked_20px.png"))); // NOI18N
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 20, 20));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 200, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Already have an account?");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 200, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        username.setText("");
    }//GEN-LAST:event_usernameFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void reg_unameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_unameFocusGained
        reg_uname.setText("");
    }//GEN-LAST:event_reg_unameFocusGained

    private void reg_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_passFocusGained
        reg_pass.setText("");
    }//GEN-LAST:event_reg_passFocusGained

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setExtendedState(Registration_Form.ICONIFIED);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void reg_lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_lnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_lnameFocusGained

    private void reg_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_lnameActionPerformed

    private void reg_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_fnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_fnameFocusGained

    private void reg_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_fnameActionPerformed

    private void reg_pass_confirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_pass_confirmFocusGained
        reg_pass_confirm.setText("");
    }//GEN-LAST:event_reg_pass_confirmFocusGained

    private void reg_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_emailFocusGained
        reg_email.setText("");
    }//GEN-LAST:event_reg_emailFocusGained

    private void reg_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_passActionPerformed

    private void reg_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_unameActionPerformed

    private void reg_pass_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_pass_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_pass_confirmActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Login_Form login = new Login_Form();
        login.show();
        
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void register_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_btnMouseClicked
        // To submit a register:
        String PASSWORD = new String(reg_pass.getPassword());
        String CON_PASSWORD = new String(reg_pass_confirm.getPassword());
        if (reg_fname.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The first name field is empty.");
        }
        else if(reg_lname.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The last name field is empty.");
        }
        else if(reg_uname.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The username field is empty.");
        }
        else if(reg_pass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The password field is empty.");
        }
        else if(reg_pass_confirm.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The confirm password field is empty.");
        }
        else if(!PASSWORD.equals(CON_PASSWORD)){
            JOptionPane.showMessageDialog(null,"The password does not match with the confirm password.");
        }
        else if(reg_email.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"The email field is empty.");
        }
        else{
            try{
                String sql = "Insert into account(id,fname,lname,uname,pass, email, user_type)values(id,?,?,?,?,?,?)";
                pstmt = conn.prepareStatement(sql);
                pstmt.setString(1,reg_fname.getText());
                pstmt.setString(2,reg_lname.getText());
                pstmt.setString(3,reg_uname.getText());
                pstmt.setString(4,reg_pass.getText());
                pstmt.setString(5,reg_email.getText());
                pstmt.setString(6,"user");

                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Registration Successful");
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_register_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField reg_email;
    private javax.swing.JTextField reg_fname;
    private javax.swing.JTextField reg_lname;
    private javax.swing.JPasswordField reg_pass;
    private javax.swing.JPasswordField reg_pass_confirm;
    private javax.swing.JTextField reg_uname;
    private javax.swing.JLabel register_btn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
